#!/usr/bin/env ruby
lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)
require 'saw'
opts = {:trace => false, :filename => '/tmp/saw.log', :console_level => 'debug', :file_level => 'summary' }

log = Saw::Logger.setup_logger(opts)

log.footprint("footprint")
log.debug("debug")
log.info("info")
log.summary("summary")
log.warn("warn")
log.error("error")
log.fatal("fatal")

